### Numpy

In [1]:
from MFEA_lib.tasks.Benchmark import *
from scipy.io import loadmat
import os


In [1]:
import numpy as np

In [11]:
np.append([np.random.permutation(10)], [np.random.randint(0, 10, 10)], axis= 0)

array([[2, 8, 9, 1, 5, 6, 7, 0, 4, 3],
       [8, 8, 3, 2, 1, 9, 6, 0, 4, 3]])

array([3, 1, 6, 1, 1, 5, 2, 4, 8, 0])

In [3]:
from MFEA_lib.tasks.Benchmark import CEC17_benchmark

In [4]:
tasks = CEC17_benchmark.get_10tasks_benchmark()

In [6]:
tasks[0](np.zeros((50,)) + 0.5)

0.0

In [4]:
CEC17_benchmark.get_2tasks_benchmark(2)

In [14]:
path = os.path.dirname(os.path.realpath(__file__))


NameError: name '__file__' is not defined

In [5]:
import numpy as np
import time

In [10]:
l = int(1e8)
a = [1] * l
b = np.ones((l))


In [13]:
s = time.time()
for i in a:
    1 + 1
print(time.time() - s)

2.6245357990264893


In [14]:
s = time.time()
for i in b:
    1 + 1
print(time.time() - s)

7.461835861206055


In [12]:
a = [1, 2, 3]

### tasks

In [1]:
from MFEA_lib.tasks import Benchmark

In [2]:
cec17 = Benchmark.CEC17_benchmark.get_10tasks_benchmark()

In [15]:
for t in cec17:
    print(t.name)

Sphere: [-100, 100]^50
Sphere: [-100, 100]^50
Sphere: [-100, 100]^50
Weierstrass: [-0.5, 0.5]^25
Rosenbrock: [-50, 50]^50
Ackley: [-50, 50]^50
Weierstrass: [-0.5, 0.5]^50
Schwefel: [-500, 500]^50
Griewank: [-100, 100]^50
Rastrigin: [-50, 50]^50


In [16]:
for t in cec17:
    print(t.global_optimal[[0, -1]])

[0. 0.]
[80. 80.]
[-80. -80.]
[-0.4 -0.4]
[0. 0.]
[40. 40.]
[-0.4 -0.4]
[420.9687 420.9687]
[-80.  80.]
[ 40. -40.]


In [17]:
print(cec17[0].encode(cec17[0].global_optimal)[[0, -1]])
print(cec17[1].encode(cec17[1].global_optimal)[[0, -1]])
print(cec17[2].encode(cec17[2].global_optimal)[[0, -1]])
print(cec17[3].encode(cec17[3].global_optimal)[[0, -1]])
print(cec17[4].encode(cec17[4].global_optimal)[[0, -1]])
print(cec17[5].encode(cec17[5].global_optimal)[[0, -1]])
print(cec17[6].encode(cec17[6].global_optimal)[[0, -1]])
print(cec17[7].encode(cec17[7].global_optimal)[[0, -1]])
print(cec17[8].encode(cec17[8].global_optimal)[[0, -1]])
print(cec17[9].encode(cec17[9].global_optimal)[[0, -1]])

[0.5 0.5]
[0.9 0.9]
[0.1 0.1]
[0.1 0.1]
[0.5 0.5]
[0.9 0.9]
[0.1 0.1]
[0.9209687 0.9209687]
[0.1 0.9]
[0.9 0.1]


shift

encode: đầu vào là không gian đã dịch chuyển

> R' -bound-> bounded_space -encode-> [0, 1] 

decode: đầu vào là không gian mã hóa [0, 1] 

>[0, 1] -decode-> bounded_space -unbound-> R' -inv_shift-> R

In [18]:
cec17_2 = Benchmark.CEC17_benchmark.get_10tasks_benchmark()

In [19]:
cec17[0]

In [20]:
cec17_2[0]

In [21]:
cec17[0] == cec17_2[0]

True

### EA

In [1]:
from MFEA_lib.EA import *


#### Population

In [23]:
popTest = Population(
    nb_inds_tasks= [2] * 10,
    dim = 50,
    list_tasks= cec17
)
popTest

In [24]:
popTest2 = Population(
    nb_inds_tasks= [2] * 10,
    dim = 50,
    list_tasks= cec17
)
popTest2

In [25]:
c = popTest + popTest2
c

In [3]:
a = [1, 2, 3]
a[:] = 1
a

TypeError: can only assign an iterable

In [26]:
for subpop in popTest:
    print(subpop)

In [16]:
print(len(popTest))
print(len(popTest2))
print(len(c))

20
20
40


In [17]:
popTest[0][:]

[Genes: [0.45947111 0.65439664 0.18994956 0.13192798 0.84896402 0.06942177
  0.82264809 0.57749498 0.88322693 0.87137015 0.93131322 0.78772747
  0.5864816  0.65998857 0.6177119  0.31168854 0.60898381 0.80852219
  0.61594408 0.09004769 0.25306111 0.62354365 0.10167681 0.88323335
  0.29370913 0.86177707 0.16559398 0.11647316 0.47582964 0.59440099
  0.08891621 0.01011002 0.47686353 0.82054785 0.77870723 0.46198477
  0.29583552 0.73124243 0.36576184 0.48025064 0.85467614 0.29701332
  0.21951394 0.826859   0.85778467 0.10248773 0.04497189 0.70075426
  0.11153138 0.0286998 ]
 Skill_factor: 0,
 Genes: [2.60070481e-01 3.42692977e-01 6.77034952e-04 1.07286135e-01
  6.44066692e-01 7.43382789e-01 4.34341401e-01 3.15315189e-01
  6.79056198e-01 3.04511088e-01 6.59737391e-01 8.12879716e-01
  8.13717480e-01 3.41721908e-01 6.51667835e-02 4.62001612e-01
  7.92285701e-01 9.34100879e-01 7.80713454e-01 5.78264910e-01
  2.99406822e-01 9.09629429e-01 7.85257711e-01 1.22852189e-01
  6.65296498e-01 3.54226295

In [18]:
popTest2[0][:]

[Genes: [0.82892775 0.79816369 0.56022747 0.03021418 0.5024879  0.18200236
  0.84528297 0.77074019 0.54366947 0.65131891 0.65634436 0.6479757
  0.23394993 0.08217486 0.55098001 0.85189555 0.69363443 0.69677835
  0.0752396  0.84169931 0.31404796 0.87900121 0.74040185 0.7235703
  0.86846199 0.38311545 0.57692931 0.23112128 0.41424989 0.7171158
  0.69490907 0.51992646 0.09952947 0.61006526 0.92069939 0.90221661
  0.56570379 0.41955928 0.73212179 0.03102349 0.85860445 0.82236038
  0.70989038 0.07671339 0.44575211 0.53183818 0.416701   0.1652926
  0.57103226 0.59227731]
 Skill_factor: 0,
 Genes: [0.56967613 0.38899932 0.22729011 0.80218592 0.73740521 0.78327004
  0.40968835 0.78085118 0.09016254 0.09964342 0.43008867 0.88246874
  0.51255303 0.15435262 0.44542364 0.67864957 0.73727347 0.53330822
  0.38787257 0.38359849 0.63086707 0.29967474 0.52894932 0.49638093
  0.37845643 0.35675932 0.67911513 0.11033451 0.92937792 0.61108682
  0.19083378 0.05109215 0.28743289 0.35543157 0.59104417 0.6583

In [19]:
c[0][:]

[Genes: [0.45947111 0.65439664 0.18994956 0.13192798 0.84896402 0.06942177
  0.82264809 0.57749498 0.88322693 0.87137015 0.93131322 0.78772747
  0.5864816  0.65998857 0.6177119  0.31168854 0.60898381 0.80852219
  0.61594408 0.09004769 0.25306111 0.62354365 0.10167681 0.88323335
  0.29370913 0.86177707 0.16559398 0.11647316 0.47582964 0.59440099
  0.08891621 0.01011002 0.47686353 0.82054785 0.77870723 0.46198477
  0.29583552 0.73124243 0.36576184 0.48025064 0.85467614 0.29701332
  0.21951394 0.826859   0.85778467 0.10248773 0.04497189 0.70075426
  0.11153138 0.0286998 ]
 Skill_factor: 0,
 Genes: [2.60070481e-01 3.42692977e-01 6.77034952e-04 1.07286135e-01
  6.44066692e-01 7.43382789e-01 4.34341401e-01 3.15315189e-01
  6.79056198e-01 3.04511088e-01 6.59737391e-01 8.12879716e-01
  8.13717480e-01 3.41721908e-01 6.51667835e-02 4.62001612e-01
  7.92285701e-01 9.34100879e-01 7.80713454e-01 5.78264910e-01
  2.99406822e-01 9.09629429e-01 7.85257711e-01 1.22852189e-01
  6.65296498e-01 3.54226295

#### SubPop

In [20]:
subPopTest = SubPopulation(
    skill_factor= 0,
    num_inds= 100,
    dim= 50,
    task= cec17[0]
)
subPopTest

In [21]:
i = 0
subPopTest1 = SubPopulation(
    skill_factor= i,
    num_inds= 100,
    dim= 50,
    task= cec17[i]
)
subPopTest1

In [22]:
subPopTest[[1, 3]]

[Genes: [0.45401143 0.48308908 0.74537716 0.33642418 0.78191076 0.95148028
  0.71787959 0.98605442 0.99550558 0.72638121 0.3217523  0.97994968
  0.70997773 0.84276777 0.88705273 0.71878093 0.44904558 0.7438054
  0.34228124 0.46227372 0.30307873 0.23203655 0.68498679 0.79678691
  0.83050336 0.92591799 0.42288656 0.52200825 0.15108608 0.45584142
  0.70273784 0.99362511 0.81953476 0.53480827 0.08570323 0.73631016
  0.48866039 0.87363827 0.99267286 0.67891569 0.98817744 0.62647053
  0.46030713 0.55752415 0.14039502 0.92236823 0.58326103 0.42075589
  0.68413919 0.05964112]
 Skill_factor: 0,
 Genes: [0.26445608 0.22813851 0.15484065 0.29827476 0.5741057  0.23343898
  0.47719628 0.12539063 0.73043621 0.60755955 0.78826291 0.70817742
  0.38279451 0.5671446  0.18791924 0.53619209 0.83387832 0.65439037
  0.24023266 0.69144594 0.14931052 0.05662877 0.00423042 0.12608399
  0.94602655 0.16951778 0.46717255 0.35085479 0.94484531 0.53912587
  0.75627336 0.47040701 0.72285895 0.28227974 0.72924548 0.9

In [23]:
c = subPopTest + subPopTest1
c

In [24]:
len(c)

200

In [25]:
a = subPopTest.ls_inds

In [26]:
c.factorial_rank

array([ 48, 104,   7,  59, 154,  29, 183,  65, 185,   4, 198,  90,  22,
        68,  37, 118, 171,  74, 106, 190, 153, 158,  49,  27,  89,  38,
        36,  52, 142, 122,   6,  18, 199,  41,  45,  63,  39, 126, 175,
        23, 155, 149, 135,  60,  25,  53, 140, 176,  34,  93,  79,  87,
       117, 152, 127,  17,  95,  10,  71, 179,  97,   3, 121,  72,  14,
       191, 124,  61,  83, 193, 173,   9,   8,  69, 163, 196,  13, 120,
        11, 166, 132,  98, 141, 160,  81,  43, 186, 123, 170, 144,  80,
        51, 180, 159,  20,  19, 136,  96, 172,  33,  66, 131,  94, 165,
       108,  91,   1, 100, 148, 115, 138,   5,  26, 143, 112, 133,  77,
       107, 164, 110, 147,  44, 114,  76, 181,  73,  46, 162,  86, 130,
       167,  67, 116, 195, 109,  78,  99,  56,  31,  64, 113,  58, 169,
        42, 197, 161,  50,  75,  12,  16,  62, 102,  40, 119, 134,  70,
        54,  28,  55, 189, 156, 137, 125, 103, 192,  32,  47,  84, 128,
       139, 187,  57, 174, 188, 145,  85, 111,   2,  30, 168,  1

#### Individual

In [2]:
a = Individual(np.arange(10))
a.skill_factor = 0
a.fcost = 1

In [4]:
a.dim

10

In [33]:
b = Individual(np.arange(10, 20))
b.skill_factor = 0
b.fcost = 1

In [34]:
c = Individual(np.arange(5, 15))
c.skill_factor  = 1
c.fcost = 1

In [35]:
a == b

True

In [37]:
a is b

False

In [36]:
a == c

False

In [38]:
a

Genes: [0 1 2 3 4 5 6 7 8 9]
Skill_factor: 0

In [39]:
b

Genes: [10 11 12 13 14 15 16 17 18 19]
Skill_factor: 1

In [40]:
c

Genes: [ 5  6  7  8  9 10 11 12 13 14]
Skill_factor: 0

In [41]:
a + b

Genes: [10 12 14 16 18 20 22 24 26 28]
Skill_factor: 0

In [42]:
a - b

Genes: [-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
Skill_factor: 0

In [43]:
a * b

Genes: [  0  11  24  39  56  75  96 119 144 171]
Skill_factor: 0

In [44]:
a / b

Genes: [0.         0.09090909 0.16666667 0.23076923 0.28571429 0.33333333
 0.375      0.41176471 0.44444444 0.47368421]
Skill_factor: 0

In [45]:
a // b

Genes: [0 0 0 0 0 0 0 0 0 0]
Skill_factor: 0

In [46]:
a % b

Genes: [0 1 2 3 4 5 6 7 8 9]
Skill_factor: 0

In [47]:
a ** b

Genes: [                  0                   1                4096
             1594323           268435456         30517578125
       2821109907456     232630513987207   18014398509481984
 1350851717672992089]
Skill_factor: 0

In [48]:
a < b

False

In [49]:
a < c

True

In [50]:
idx = np.random.choice(10, 3)
idx

array([7, 8, 5])

In [51]:
a

Genes: [0 1 2 3 4 5 6 7 8 9]
Skill_factor: 0

In [52]:
b

Genes: [10 11 12 13 14 15 16 17 18 19]
Skill_factor: 1

In [53]:
a[idx]

array([7, 8, 5])

In [54]:
b[idx]

array([17, 18, 15])

In [55]:
a[idx] = b[idx]

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
a.genes[idx] = b.genes[idx]

In [ ]:
a

Genes: [10  1  2  3  4  5  6  7 18 19]
Skill_factor: 0