In [ ]:
import pandas as pd 
import numpy as np 

In [4]:
a = {'0': 10, '1': 20} 

if '0' in a.keys(): 
    print("okey")

okey


In [10]:
class A:
    def __init__(self):
        pass

    def compile(self, b):
        b.tasks = 1 
        self.b = b 
        

class B: 
    def __init(self): 
        self.tasks = 0 
        pass 


a = A()
a.compile(B()) 
getattr(getattr(a, 'b'), 'tasks')


1

In [10]:
import numpy as np 

mean= np.array([1,2]) 
cov = np.array([[1,0], [0,1]])

np.random.multivariate_normal(mean, cov)

array([0.94583735, 2.40348754])

In [15]:
a = np.array([[1,2,3], [1,2,3]]) 
print(a)
print(np.mean(a, axis= 0))

[[1 2 3]
 [1 2 3]]
[1. 2. 3.]


In [ ]:
a = np.random.rand(20,10)

In [ ]:
a = [1, 2, 4] 
b = a.copy() 
b[2] = 3 

In [ ]:
print(b)
print(a)

In [ ]:
a = {
    'lr': [0,1, 2, 4], 
    'ma': [2,3,4],
    'crossover':{
        'gamma': [0.3, 0.4]
    }
}

a = list(a.items()) 
print(a)
print(type(a[0]))


In [ ]:
for i in range(len(a)): 
    a[i] = list(a[i])
print(a)

In [ ]:
for key, value in a : 
    print(a.index((key, value)))

In [ ]:
for key, value in a : 
    print(key)
a[0][1].insert(0, -2)
a[0][1]



In [ ]:
class a: 
    def __init__(self)

In [ ]:
a = [1, 3, 4]
a.insert(0, -1) 
print(a)

In [ ]:
from MFEA_lib.model.utils import * 

model  = loadModel("./RESULTS/tuning_smp/check.mso")

In [ ]:
getattr

In [ ]:
setattr(model.compile_kwargs['crossover'], 'gamma', 0.4)

In [ ]:
getattr(model.compile_kwargs['crossover'], 'gamma')

In [ ]:
for key, value in model.compile_kwargs.items(): 
    print(key)

In [ ]:
print(model.kwargs.items())

In [ ]:
a = [-1, -2, -3, -1] 
a.remove(-1)
a.remove(-1)

In [ ]:
import os 
os.makedirs("./RESULTS/ahihi.01/")
path = os.path.join("./RESULTS/ahihi/a/")
os.makedirs(path+"ma")

In [ ]:
os.path.isdir("./RESULTS/SMP/gamma/0.4/")

In [ ]:
import shutil
shutil.rmtree("./RESULTS/ahihi")

In [ ]:

os.removedirs("./RESULTS/ahihi")

In [ ]:
print(a)

In [ ]:
for key, value in model.kwargs.items(): 
    print(value)
    print(key)

In [ ]:
a = [1, 2]
a = pd.DataFrame([a], index=["com"])
print(a)

In [ ]:
a = a.astype(str)

In [ ]:
a.iloc[0][0] = str("ad") + a.iloc[0][0]

In [ ]:
print(a)

In [ ]:
import numpy as np 
a = [[1,2],[4,3]]
name_row = ["task1", "task2"]
name_col = ["alg_1", "alg_2"]


In [ ]:
a = pd.DataFrame(a)

In [ ]:
a

In [ ]:
a.iloc[0][1]

In [ ]:
a = [1,2,3,4,5,6]

In [ ]:
for i in a[:-1]:
    print(i)

In [ ]:
print(a)

In [ ]:
a.index = name_row
a.columns = name_col
print(a)

In [ ]:
df = pd.DataFrame(a, columns=name_col, index = name_row)

In [ ]:
print(a)

In [ ]:
print(df)

In [ ]:
print(df)

In [ ]:
df.loc[['task1']] = 'str' + df.loc[['task1']].astype(str)

In [ ]:
print(df)

In [ ]:
df['task1', :] = str("1") + df['task1', :].astype(str)

In [ ]:
for row in range(len(name_row)-1): 
    argmin = np.argmin(a[row])
    df

In [ ]:
a = pd.DataFrame(a)

In [ ]:
a = str("-oma") + a[1].astype(str)
print(a)

In [ ]:
print(a)

In [ ]:
a = np.array(a, dtype= '<U3')

In [ ]:
def ahihi(add):
    pass 
    print(add) 

In [ ]:
ahihi(10)


In [ ]:
print(pd.DataFrame(a,))

In [ ]:
arr = []
for i in range(10):
    arr.append(np.arange(i, 1000, 50).tolist())
print(arr)

In [ ]:
def readFileTM(path):
    his_raw = pd.read_csv(path, header= None, usecols= np.arange(1, 301).tolist()).to_numpy()
    arr = []
    for i in range(10):
        arr.append(np.arange(i, 300, 10).tolist())
    arr = np.array(arr)
    history_cost = np.zeros((1000, 10))
    try:
        for idx, idx_arr in enumerate(arr):
            history_cost[:, idx] = np.average(his_raw[:, arr[idx]], axis = 1)
    except:
        print()
    return history_cost

In [ ]:
import os 
import pandas as pd
import numpy as np 
name = ["EBS_GA", "SA", "LSA","MFEA", "MaTDE", "MaTGA", 'SBS_GA_poly', 'SBS_GA']
ls_history_cost = []
ls_history_cost_task = {}
path = "D:/LinhTinh/result_run_cec_gecco/seed_0_to_20"
remain_path = "D:/LinhTinh/result_run_cec_gecco/seed_20_to_30"
list_algo = os.listdir(path) 

for idx_algo  in range(len(list_algo)): 
    print(name[idx_algo])
    algorithm = list_algo[idx_algo] 
    # if idx_algo == 4 or idx_algo == 2:
    #     continue
    # if idx_algo != 4: 
    #     continue
    if idx_algo > 0: 
        break 
    # take the benchmark 
    benchmarks = os.listdir(os.path.join(path, algorithm))
    assert len(benchmarks) == 10 
    path_algo = os.path.join(path, algorithm) 
    for benchmark in benchmarks: 
        # 20 seed first
        path_benchmark = os.path.join(path_algo, benchmark) 
        result_link = os.path.join(path_benchmark, os.listdir(path_benchmark)[0])
        # print(result_link)
        result = pd.read_csv(result_link, header=None).to_numpy()
        print(result.shape)
        # print(result[0][1:].shape)
        result = result[0][1:] # shape = (1000,)
        # 10 seed end 
        path_remained_bechmark = os.path.join(os.path.join(remain_path, algorithm), benchmark)
        result_link_2 = os.path.join(path_remained_bechmark, os.listdir(path_remained_bechmark)[0])
        # print(result_link_2)
        result_2 = pd.read_csv(result_link_2, header=None).to_numpy()
        result_2 = result_2[0][1001:]
        # print(result_2.shape)
        # calculat 
        # concate
        result = np.concatenate([result, result_2], axis= 0)
        print(result.shape)
        # result.reshape((1000,1))
        
        history_cost = np.zeros(shape=(1000, 50))
        arr = [] 
        for idx_task in range(50): 
            arr.append(np.arange(idx_task, 1500, 50).tolist())
        arr = np.array(arr)
        
        for idx, task in enumerate(arr): 
            history_cost[:, idx] = np.average(result[arr[idx]])
        
        ls_history_cost.append(history_cost.tolist())
        ls_history_cost_task[str(name[idx_algo]) + "_"+ benchmark] = history_cost


In [ ]:
import os 
import pandas as pd
import numpy as np 
name = ["EBS_GA", "SA", "LSA","MFEA", "MaTDE", "MaTGA", 'SBS_GA_poly', 'SBS_GA']
ls_history_cost = []
ls_history_cost_task = {}
path = "D:/LinhTinh/result_run_cec_gecco/seed_0_to_20"
remain_path = "D:/LinhTinh/result_run_cec_gecco/seed_20_to_30"
list_algo = os.listdir(path) 

for idx_algo  in range(len(list_algo)): 
    print(name[idx_algo])
    algorithm = list_algo[idx_algo] 
    # if idx_algo == 4 or idx_algo == 2:
    #     continue
    # if idx_algo != 4: 
    #     continue
    if idx_algo > 0: 
        break 
    # take the benchmark 
    benchmarks = os.listdir(os.path.join(path, algorithm))
    assert len(benchmarks) == 10 
    path_algo = os.path.join(path, algorithm) 
    for benchmark in benchmarks: 
        # 20 seed first
        path_benchmark = os.path.join(path_algo, benchmark) 
        result_link = os.path.join(path_benchmark, os.listdir(path_benchmark)[0])
        # print(result_link)
        result = pd.read_csv(result_link, header=None).to_numpy()
        print(result.shape)
        # print(result[0][1:].shape)
        result = result[0][1:] # shape = (1000,)
        # 10 seed end 
        path_remained_bechmark = os.path.join(os.path.join(remain_path, algorithm), benchmark)
        result_link_2 = os.path.join(path_remained_bechmark, os.listdir(path_remained_bechmark)[0])
        # print(result_link_2)
        result_2 = pd.read_csv(result_link_2, header=None).to_numpy()
        result_2 = result_2[0][1001:]
        # print(result_2.shape)
        # calculat 
        # concate
        result = np.concatenate([result, result_2], axis= 0)
        print(result.shape)
        # result.reshape((1000,1))
        
        history_cost = np.zeros(shape=(1000, 50))
        arr = [] 
        for idx_task in range(50): 
            arr.append(np.arange(idx_task, 1500, 50).tolist())
        arr = np.array(arr)
        
        for idx, task in enumerate(arr): 
            history_cost[:, idx] = np.average(result[arr[idx]])
        
        ls_history_cost.append(history_cost.tolist())
        ls_history_cost_task[str(name[idx_algo]) + "_"+ benchmark] = history_cost


In [ ]:
import numpy as np 

a = np.array([[1,2],[3,4]]) 
np.average(a, axis = 1)

In [ ]:
a[:][1:]

In [ ]:
import os 

name = ["EBS_GA", "SA", "LSA","MFEA", "MaTDE", "MaTGA", 'SBS_GA_poly', 'SBS_GA']
ls_history_cost = []
ls_history_cost_task = {}
path = "D:/LinhTinh/result_run_cec_gecco/seed_0_to_20"
remain_path = "D:/LinhTinh/result_run_cec_gecco/seed_20_to_30"
list_algo = os.listdir(path) 

for idx_algo  in range(len(list_algo)): 
    print(name[idx_algo])
    algorithm = list_algo[idx_algo] 
    # if idx_algo == 1 or idx_algo == 4 or idx_algo == 2:
    #     continue
    if idx_algo != 1: 
        continue
    # if idx_algo > 0: 
    #     break 
    # take the benchmark 
    benchmarks = os.listdir(os.path.join(path, algorithm))
    assert len(benchmarks) == 10 
    path_algo = os.path.join(path, algorithm) 
    for benchmark in benchmarks: 
        # 20 seed first
        path_benchmark = os.path.join(path_algo, benchmark) 
        path_benchmark = os.path.join(path_benchmark, os.listdir(path_benchmark)[0])
        result_link = os.path.join(path_benchmark, os.listdir(path_benchmark)[0])
        # print(result_link)
        result = pd.read_csv(result_link, header=None).to_numpy()
        # print(result[0][1:].shape)
        result = result[0][1:] # shape = (1000,)
        # 10 seed end 
        path_remained_bechmark = os.path.join(os.path.join(remain_path, algorithm), benchmark)
        path_remained_bechmark = os.path.join(path_remained_bechmark, os.listdir(path_remained_bechmark)[0])
        result_link_2 = os.path.join(path_remained_bechmark, os.listdir(path_remained_bechmark)[0])
        # print(result_link_2)
        result_2 = pd.read_csv(result_link_2, header=None).to_numpy()
        result_2 = result_2[0][1001:]
        # print(result_2.shape)
        # calculat 
        # concate
        result = np.concatenate([result, result_2], axis= 0)
        print(result.shape)
        # result.reshape((1000,1))
        
        history_cost = np.zeros(shape=(1000, 50))
        arr = [] 
        for idx_task in range(50): 
            arr.append(np.arange(idx_task, 1500, 50).tolist())
        arr = np.array(arr)
        
        for idx, task in enumerate(arr): 
            history_cost[:, idx] = np.average(result[arr[idx]])
        
        ls_history_cost.append(history_cost.tolist())
        ls_history_cost_task[str(name[idx_algo]) + "_"+ benchmark] = history_cost


In [7]:

from MFEA_lib.model import AbstractModel
from MFEA_lib.model.utils import *
import pandas as pd
import numpy as np
import scipy.io
from MFEA_lib.tasks.Benchmark.Funcs import * 
from MFEA_lib.operators.Crossover import *
from MFEA_lib.operators.Mutation import *
from MFEA_lib.operators.Selection import *



In [5]:
import os 
import pandas as pd
import numpy as np 
# name = ["EBS_GA", "SA", "LSA","MFEA", "MaTDE", "MaTGA", 'SBS_GA_poly', 'SBS_GA']
name = ['LSA_2021']
ls_history_cost = []
ls_history_cost_task = {}
# path = "/home/tanminh/Downloads/MTO-Competition-CEC21/results/"
# path = "D:/LinhTinh/MTO-Competition-CEC21/MTO-Competition-CEC21/results/results/"
path="/media/tanminh/New Volume/LinhTinh/Ubuntu/MTO-Competition-CEC21/results"
remain_path = "D:/LinhTinh/result_run_cec_gecco/seed_20_to_30"
list_algo = ['MTO-Complex']

for idx_algo  in range(len(list_algo)): 
    print(name[idx_algo])
    algorithm = list_algo[idx_algo] 

    benchmarks = os.listdir(os.path.join(path, algorithm))
    # print(benchmark
    for benchmark in benchmarks: 
        # 20 seed first
        path_benchmark = os.path.join(os.path.join(path, algorithm), benchmark) 
        # path_benchmark = os.path.join(path_benchmark, os.listdir(path_benchmark)[0])
        result_link = path_benchmark
        # print(result_link)
        result = pd.read_csv(result_link, header=None).to_numpy()
        # print(result[0][1:].shape)
        # print(result.shape)
        print(benchmark)
        result = result[:,1:] # shape = (1000,)
        # 10 seed end
        print(result.shape)
        # result.reshape((1000,1))
        
        history_cost = np.zeros(shape=(100, 2))
        arr = [] 
        for idx_task in range(2): 
            arr.append(np.arange(idx_task, 2 * 30,2).tolist())
        arr = np.array(arr)
        
        for idx, task in enumerate(arr): 
            history_cost[:, idx] = np.average(result[:,arr[idx]], axis= 1)
        
        ls_history_cost.append(history_cost.tolist())
        ls_history_cost_task[str(name[idx_algo]) + "_"+ benchmark] = history_cost

LSA_2021
MTOSOO_P1.txt
(100, 60)
MTOSOO_P10.txt
(100, 60)
MTOSOO_P2.txt
(100, 60)
MTOSOO_P3.txt
(100, 60)
MTOSOO_P4.txt
(100, 60)
MTOSOO_P5.txt
(100, 60)
MTOSOO_P6.txt
(100, 60)
MTOSOO_P7.txt
(100, 60)
MTOSOO_P8.txt
(100, 60)
MTOSOO_P9.txt
(100, 60)


In [ ]:
np.array(ls_history_cost[2]).shape

In [16]:
ls_history_cost_task["LSA_2021_MTOMSO_P10.txt"].shape

(1000, 50)

In [3]:
model3 = MultiTimeModel(AbstractModel, name= "LSA_2021_MTOMSO_P5.txt")
model3.set_data(ls_history_cost_task["LSA_2021_MTOMSO_P5.txt"])
model3.tasks = None
saveModel(model3, PATH = "./RESULTS/MODEL3.mso", remove_tasks= False)

Set complete!


'Saved'

In [4]:
model4 = loadModel("./RESULTS/MODEL3.mso", GECCO20_benchmark_50tasks.get_items(5))

In [8]:
for key, value in ls_history_cost_task.items(): 
    print(key)
    model = MultiTimeModel(AbstractModel, name=key) 
    model.nb_run = 30
    key = str(key).split(".")[0]
    key = str(key).split("_")[-1] # P3
    id = int(str(key[1:]))
    print(key)
    print(id)
    # model.tasks = CEC17_benchmark.get_2tasks_benchmark(ID = id)
    model.tasks = None 
    model.set_data(value) 
    path = "./RESULTS/result/LSA_2021_MTOMSO_Benchmark_" + str(id) + ".mso"
    # path = "./RESULTS/50tasks/d" + str(id) + ".mso"
    print(path) 
    print(model.history_cost[-1])
    # if id == 5: 
    #     model.render_history(yscale= 'log')
    saveModel(model, PATH=path, remove_tasks= False)



LSA_2021_MTOSOO_P1.txt
P1
1
Set complete!
./RESULTS/result/LSA_2021_MTOMSO_Benchmark_1.mso
[608.00864307 607.89137403]
LSA_2021_MTOSOO_P10.txt
P10
10
Set complete!
./RESULTS/result/LSA_2021_MTOMSO_Benchmark_10.mso
[2230.61177007 6263.21370613]
LSA_2021_MTOSOO_P2.txt
P2
2
Set complete!
./RESULTS/result/LSA_2021_MTOMSO_Benchmark_2.mso
[700.0025424  700.00328443]
LSA_2021_MTOSOO_P3.txt
P3
3
Set complete!
./RESULTS/result/LSA_2021_MTOMSO_Benchmark_3.mso
[5287.95026707 6475.5768689 ]
LSA_2021_MTOSOO_P4.txt
P4
4
Set complete!
./RESULTS/result/LSA_2021_MTOMSO_Benchmark_4.mso
[1300.30108777 1300.2617392 ]
LSA_2021_MTOSOO_P5.txt
P5
5
Set complete!
./RESULTS/result/LSA_2021_MTOMSO_Benchmark_5.mso
[1507.4175862  1508.07395407]
LSA_2021_MTOSOO_P6.txt
P6
6
Set complete!
./RESULTS/result/LSA_2021_MTOMSO_Benchmark_6.mso
[6826.39746537 5556.1439513 ]
LSA_2021_MTOSOO_P7.txt
P7
7
Set complete!
./RESULTS/result/LSA_2021_MTOMSO_Benchmark_7.mso
[2562.7353261  2605.39661367]
LSA_2021_MTOSOO_P8.txt
P8
8
Set 

In [7]:
model = loadModel("./RESULTS/50tasks/dm5.mso", GECCO20_benchmark_50tasks.get_items(2))

In [ ]:

for id in range(9, 11):
    print(id)
    model = loadModel("./RESULTS/50tasks/LSA_2021_MTOMSO_Benchmark_{}.mso".format(str(id)))

In [ ]:
model.history_cost.shape

In [ ]:
model = loadModel('./RESULTS/50tasks/SBS_GA_poly_Benchmark_3.mso')

In [ ]:
model2 = loadModel('./RESULTS/50tasks/SBS_GA_poly_Benchmark_3.mso')

In [ ]:

model = loadModel('./RESULTS/50tasks/SBS_GA_poly_Benchmark_3.mso')
model2 = loadModel('./RESULTS/50tasks/SBS_GA_poly_Benchmark_3.mso')
compare = CompareModel([model, model2]) 
compare.compareResult()

In [ ]:
model.name

In [ ]:
model.render_history(yscale= 'log')
print()


In [ ]:
ls_history_cost_task

In [ ]:
ls_history_cost[0]


In [ ]:
print(len(ls_history_cost))

<h1>Test IDPC-EDU </h1>

In [ ]:
data = [] 
with open("/MFEA_lib/tasks/__references__/IDPC_DU/IDPC_EDU/data/set1/idpc_10x5x425.idpc") as f: 
    data = f.readlines() 

In [ ]:
from MFEA_lib.tasks.task import * 

idpc = IDPC_EDU(path="/__references__/IDPC_DU/IDPC_EDU/data/set1/idpc_10x5x425.idpc")

<h2>Population</h2>

In [ ]:
from MFEA_lib.EA import * 
from MFEA_lib.tasks.Benchmark import CEC17_benchmark
cec = CEC17_benchmark.get_10tasks_benchmark()
a = SubPopulation(1, 10, 50, bound=[0,1], task=cec[1])

In [ ]:
a[0]

In [ ]:
class B(): 
    def __init__(self): 
        self.b  = 10 
        self.c = 10 

In [ ]:
class A() : 
    def __init__(self): 
        self.ls_inds = [B() for i in range(10)]
    def __getitem__(self, index): 
        return self.ls_inds[index] 
    
    

a = A() 


In [ ]:
from MFEA_lib.EA import * 
from MFEA_lib.tasks import Benchmark


In [ ]:
cec17 = Benchmark.CEC17_benchmark.get_10tasks_benchmark()

In [ ]:
a = np.array([0.9] * 25 + [0.1] * 25) 
print(cec17[9].func(a))
b = np.array( [0.89999999992] * 1 + [0.9] * 24 + [0.1] * 24 + [0.10000000009] * 1)
print(cec17[9].func(b))

In [ ]:
a = np.array([0.8999999999999999] * 50) 
print(cec17[1].func(a))
b = np.array([0.8999999999999884]*49 + [0.90000000001])
print(cec17[1].func(b))

In [ ]:
a = EA.SubPopulation(skill_factor= 1, num_inds= 20, dim = 50, task= cec17[0]) 

In [ ]:
a.update_rank() 


In [ ]:
ch = np.random.choice(np.where(a.scalar_fitness >= 1/(0.1 * len(a)))[0])
print(np.where(a.scalar_fitness >= 1/(0.1 * len(a)))[0])
print(ch)

In [ ]:
type(a) == SubPopulation

In [ ]:
b = [a[i].genes[0] for i in range(len(a))]

In [ ]:
a, b = np.random.choice([3,4], size= 2 , replace= True)
print(a)
print(b)

In [ ]:
np.std(b)

In [ ]:
num_inds_tasks = np.zeros(shape = (len(cec17)), dtype= int) + 10
dim = 50

pop = Population(nb_inds_tasks = num_inds_tasks, dim = dim, list_tasks= cec17)
itemgetter(*b)

<h3> Individual </h3>

In [ ]:
ind = pop[0].__getRandomItems__(size= 1)
print(ind)

In [ ]:
pop[0][1]

In [ ]:
A = np.array([1, 2, 4, 3]) 
A[np.array([1, 2])]

In [ ]:
# a = pop[0].ls_inds[np.random.choice(np.arange(len(pop[0])), size= (3,))]
# NOTE 

b = np.random.choice(len(pop[0]), size= (3,))
array = np.zeros(shape= (3,), dtype= int) + 1 
pop[0].ls_inds[array.astype(int)]

In [ ]:
print(ind)

In [ ]:
a = pop.__getRandomInds__(size = 3)

In [ ]:
print(ind3.fcost)

In [ ]:
print(ind3.skill_factor)

In [ ]:
print([len(pop[i]) for i in range(10)])

In [ ]:
print(len(pop))

In [ ]:
from inspect import signature

def someMethod(self, arg1, kwarg1=None):
    pass

sig = signature(someMethod)
print(type(sig))
print(sig.parameters)
print(list(sig.parameters.keys())[0])
