In [2]:
from MFEA_lib.model import AbstractModel, SMP_MFEA, MFEA_base, SMP_DE
from MFEA_lib.model.utils import *
from MFEA_lib.model.utils import TuningModel
import pandas as pd
import numpy as np
import scipy.io
from MFEA_lib.tasks.Benchmark.Funcs import * 
from MFEA_lib.operators.Crossover import *
from MFEA_lib.operators.Mutation import *
from MFEA_lib.operators.Selection import *


### Draft

In [2]:
a = [4,5,6] 
for idx, d in enumerate(a[1:], start= 1):
    print(idx)
    print(d)

1
5
2
6


### Tuning Model


In [ ]:
ls_benchmark = [] 
ls_IndClass = [] 
name_benchmarks = []
for id in range(1, 10):
    # print(id) 
    b, i = WCCI22_benchmark.get_complex_benchmark(4)
    name_benchmarks.append("wcci_2tasks_" + str(id))
    ls_benchmark.append(b) 
    ls_IndClass.append(i) 

b, i = CEC17_benchmark.get_10tasks_benchmark() 
ls_benchmark.append(b)
ls_IndClass.append(i)
name_benchmarks.append("CEC_10_")

In [4]:
ls_benchmark = [] 
ls_IndClass = [] 
for id in range(1, 3): 
    b, i = CEC17_benchmark.get_2tasks_benchmark(id) 
    ls_benchmark.append(b) 
    ls_IndClass.append(i) 

b, i = CEC17_benchmark.get_10tasks_benchmark() 
ls_benchmark.append(b)
ls_IndClass.append(i)

In [5]:
model = TuningModel(
    model_name= SMP_MFEA, 
    list_parameter= [
        ('crossover', {
            'gamma': [0.4, 0.6]
        }), 
        ('lr', [0.04, 0.05]),
        ('crossover', {
            'alpha': [5, 7]
        }), 
    ],
)
model.compile(
    ls_benchmark = ls_benchmark, 
    benchmark_weights = (np.ones(shape= (3,)) / 3).tolist(), 
    name_benchmark = [str(i) for i in range(1,4)],
    ls_IndClass = ls_IndClass,

    # tasks = None,
    # IndClass= None,
    # tasks = CEC17_benchmark.get_10tasks_benchmark(),
    crossover= newSBX(nc = 2, gamma= 0.4, alpha = 6),
    # crossover= SBX_Crossover(nc = 2),
    mutation = GaussMutation(scale = 0.01),
    selection= ElitismSelection(random_percent= 0.),
    # search= SHADE(len_mem= 30, p_ontop= 0.1), 
    attr_tasks = ['crossover', 'mutation']
)

fit, com, result = model.run(
    replace_folder=True,
    min_value = 1e-6,
    
    nb_generations= 5, 
    nb_inds_each_task= 100, 
    nb_inds_min= 100,
    lr = 0.05,  
    p_const_intra= 0, 
    p_mutate= 0.1, 
    prob_search = 0.,
    nb_epochs_stop= 1000, 
    swap_po= False,
    evaluate_initial_skillFactor= True
)


 crossover

 gamma
0.4
Time: 00m 2.94s  100 % [====================>]  Pop_size: 2.00E+02  ,  Cost: 2.25E+01  2.54E+04  ,  
[0.5 0.5]
[608. 592.]
END!
DONE!
Saved
Time: 00m 2.81s  100 % [====================>]  Pop_size: 2.00E+02  ,  Cost: 2.12E+01  2.51E+04  ,  
[0.5 0.5]
[600. 600.]
END!
DONE!
Saved
Time: 00m 13.40s  100 % [====================>]  Pop_size: 1.00E+03  ,  Cost: 8.11E+04  2.67E+05  2.27E+05  3.33E+01  2.36E+09  2.12E+01  7.52E+01  1.52E+04  5.72E+01  6.40E+04  ,  
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
[560. 604. 566. 634. 622. 570. 662. 622. 582. 578.]
END!
DONE!
Saved
0.6
Time: 00m 0.86s  100 % [====================>]  Pop_size: 2.00E+02  ,  Cost: 2.56E+01  2.16E+04  ,  
[0.5 0.5]
[586. 614.]
END!
DONE!
Saved
Time: 00m 0.90s  100 % [====================>]  Pop_size: 2.00E+02  ,  Cost: 2.12E+01  2.29E+04  ,  
[0.5 0.5]
[594. 606.]
END!
DONE!
Saved
Time: 00m 4.70s  100 % [====================>]  Pop_size: 1.00E+03  ,  Cost: 8.89E+04  2.60E+05  2.39E+05  3.23E+01  2.

### Show and compare result

In [6]:
MFEA_model = loadModel('./RESULTS/MFEA_cec17.mso')
EBS_GA_model = loadModel('./RESULTS/EBS_GA_cec17.mso')
MaTDE_model = loadModel('./RESULTS/MaTDE_cec17.mso')
MaTGA_model = loadModel('./RESULTS/MaTGA_cec17.mso')
MTEA_AD_model = loadModel('./RESULTS/MTEA_AD_cec17.mso')
SA_model = loadModel('./RESULTS/SA_cec17.mso')
LSA_model = loadModel('./RESULTS/LSA_cec17.mso')
# SMP_NEWSBX = loadModel("./RESULTS/SMP_NEWSBX.mso", ls_tasks= CEC17_benchmark.get_10tasks_benchmark())


In [7]:
compare = CompareModel(
    models = [MFEA_model, EBS_GA_model, MaTDE_model, MaTGA_model, MTEA_AD_model, SA_model, LSA_model],
    label= [...] * 7 ,
)
# compare.render(    
#     shape = (2, 5),
#     min_cost= 0,
#     step= 100,
#     yscale= 'log'
# )

In [8]:
compare.detail_compare_result()

MFEA                  EBS_GA                   MaTDE  \
Task1      0.2306803683118937  1.1041796512728456e-05  5.2448509840324785e-08   
Task2    0.018171437665116218   3.681032203235758e-06  1.6047725809275885e-06   
Task3     0.06637609850485167  3.3058988094997382e-06   3.780454713321491e-13   
Task4     0.15509211361656364                  (+)0.0  1.3263066634183172e-14   
Task5       50.71698610513365       580.4145475565334   8.054459884058472e-06   
Task6     0.04081920302784129      19.878634231807037   0.0003277373502341104   
Task7       0.761665023855529   0.0030677093118668527  0.00019759556704077922   
Task8       3296.151781410698       722.3461222912298   0.0025821879342401767   
Task9    0.019118154704695252   0.0002466442088243716    0.006801872064916456   
Task10      36.08224289157316       30.49323695358462       89.16722368749038   
Compare                  0/10                    1/10                    0/10   

                          MaTGA                 MTEA_AD  \
Task1     0.0026705872776819728  1.0609301724934813e-07   
Task2      0.001115356576805881   2.990552670377746e-09   
Task3      7.99836824342369e-06   5.841638817660246e-12   
Task4    0.00018902136266731547   5.631051180898794e-13   
Task5        0.2174243104776917  1.1687145306498282e-05   
Task6       0.00788099665294391  1.4935024698721951e-05   
Task7      0.007821966536942615   0.0005110312939137884   
Task8         43.47763931314948   0.0006367085414240136   
Task9      0.007421096596115487   0.0004930758789514581   
Task10     (+)4.796823959508992      17.626749155381347   
Compare                    1/10                    0/10   

                               SA                       LSA  
Task1      3.3061538714714826e-11  (+)3.168912392798847e-18  
Task2      2.7004188231793198e-12  (+)4.115767650271555e-20  
Task3      1.2453502149219146e-15  (+)8.854797474408491e-24  
Task4                      (+)0.0                    (+)0.0  
Task5    (+)3.866938484475334e-09         17.14577598003519  
Task6       4.546695502168537e-07   (+)5.24695250211001e-11  
Task7       5.111509141874911e-06  (+)4.215767568841652e-14  
Task8       0.0006363783330016303   (+)0.000636378324998077  
Task9       2.559175094063448e-13  (+)3.700743415417188e-18  
Task10         44.540968098954075         42.21939907756904  
Compare                      2/10                      8/10

In [9]:
compare.summarizing_compare_result(path=None , idx_main_algo= 2, nb_task= 2, ls_benchmark= [CEC17_benchmark.get_2tasks_benchmark(id) for id in range(1,10)])

Better  Equal  Worse
MaTDE vs MFEA          9      0      1
MaTDE vs EBS_GA        7      0      3
MaTDE vs MaTGA         9      0      1
MaTDE vs MTEA_AD       5      0      5
MaTDE vs SA            0      0     10
MaTDE vs LSA           1      0      9

In [10]:
model = loadModel("./RESULTS/50tasks/SMP_NEWSBX/lan2_2s_newsbx_50task_1.mso")

In [11]:
model.kwargs

{'nb_generations': 1000,
 'nb_inds_each_task': 100,
 'nb_inds_min': 30,
 'lr': 0.15,
 'p_const_intra': 0,
 'p_mutate': 0.05,
 'prob_search': 0.0,
 'nb_epochs_stop': 1000,
 'swap_po': False,
 'evaluate_initial_skillFactor': True}

In [12]:
getattr(model.compile_kwargs['crossover'], '')

AttributeError: 'newSBX' object has no attribute ''

In [ ]:
compare.summarizing_compare_result(path="./RESULTS/2tasks/", idx_main_algo= 7, nb_task= 50, ls_benchmark= [GECCO20_benchmark_50tasks.get_items(id) for id in range(1,11)],min_value= 1e-6, combine= True)

['EBS_GA', 'SBS_GA', 'LSA', 'SA', 'SBS_GA_poly', 'MaTDE', 'SMP_NEWSBX', 'MaTGA', 'MFEA']


Better  Equal  Worse
MaTGA vs EBS_GA           10      0      8
MaTGA vs SBS_GA            4      0     14
MaTGA vs LSA              10      0      8
MaTGA vs SA               10      0      8
MaTGA vs SBS_GA_poly       6      0     12
MaTGA vs MaTDE            12      0      6
MaTGA vs SMP_NEWSBX        7      0     11
MaTGA vs MFEA             18      0      0

In [ ]:
compare.summarizing_compare_result(path="./RESULTS/50tasks/", idx_main_algo= 7, nb_task= 50, ls_benchmark= [GECCO20_benchmark_50tasks.get_items(id) for id in range(1,11)],min_value= 1e-6, combine= False)

['LSA_2021', 'EBS_GA', 'SBS_GA', 'LSA', 'SA', 'SBS_GA_poly', 'MaTDE', 'SMP_NEWSBX', 'MaTGA', 'MFEA']


array([[[ 0, 50,  0],
        [50,  0,  0],
        [50,  0,  0],
        [ 3, 47,  0],
        [ 0, 50,  0],
        [ 0, 50,  0],
        [ 0, 50,  0],
        [50,  0,  0],
        [50,  0,  0]],

       [[ 8,  0, 42],
        [50,  0,  0],
        [43,  0,  7],
        [44,  0,  6],
        [45,  0,  5],
        [27,  0, 23],
        [41,  0,  9],
        [50,  0,  0],
        [50,  0,  0]],

       [[ 0,  0, 50],
        [50,  0,  0],
        [50,  0,  0],
        [12,  0, 38],
        [50,  0,  0],
        [37,  0, 13],
        [50,  0,  0],
        [ 0,  0, 50],
        [50,  0,  0]],

       [[ 0, 17, 33],
        [33,  0, 17],
        [34,  0, 16],
        [31,  2, 17],
        [17, 17, 16],
        [15, 17, 18],
        [16, 17, 17],
        [34,  0, 16],
        [36,  0, 14]],

       [[15,  0, 35],
        [29,  0, 21],
        [29,  0, 21],
        [12,  1, 37],
        [28,  0, 22],
        [ 8, 11, 31],
        [33,  0, 17],
        [16,  0, 34],
        [50,  0,  0]],



In [ ]:
from plyer import notification
notification.notify(
    title='TM',
    message='xong :)))',
    app_icon=None,  # e.g. 'C:\\icon_32x32.ico'
    timeout=10,  # seconds
)

### Multi Time Model

In [ ]:
tasks, IndClass= CEC17_benchmark.get_10tasks_benchmark()

smpModel = MultiTimeModel(model= SMP_MFEA)
smpModel.compile(
    tasks= tasks,
    IndClass = IndClass,
    crossover= newSBX(nc = 2, gamma= 0.6, alpha = 7),
    mutation= GaussMutation(scale= 0.1),
    # mutation = GMMScale(alpha = 3, lenMem= 20, default_scale= 0.5),
    selection= ElitismSelection(random_percent= 0.),
    attr_tasks = ['crossover', 'mutation'],
    
)
smpModel.fit(
    nb_generations= 1000, nb_inds_each_task= 100, nb_inds_min= 100,
    lr = 0.1, p_const_intra= 0.0, p_mutate= 0.1,prob_search = 0.0,
    nb_epochs_stop= 50, 
    evaluate_initial_skillFactor= True
)
smpModel.run(
    nb_run= 2,
    save_path= './RESULTS/result/smpMFEA_cec17.mso'
)

In [ ]:
smpModel.print_result(['history_cost'])

total time: 00m 1.13s
history_cost avg: 
[2.10E+01 1.16E+04]


In [3]:
ls_benchmark = [] 
ls_IndClass = [] 
for id in range(1, 3): 
    b, i = CEC17_benchmark.get_2tasks_benchmark(id) 
    ls_benchmark.append(b) 
    ls_IndClass.append(i) 

b, i = CEC17_benchmark.get_10tasks_benchmark() 
ls_benchmark.append(b)
ls_IndClass.append(i)

smpModel = MultiBenchmark(
    ls_benchmark = ls_benchmark, 
    name_benchmark = [str(i) for i in range(1,4)],
    ls_IndClass = ls_IndClass,
    model= SMP_MFEA
    )

smpModel.compile(
    crossover= newSBX(nc = 2, gamma= 0.6, alpha = 7),
    mutation= GaussMutation(scale= 0.1),
    # mutation = GMMScale(alpha = 3, lenMem= 20, default_scale= 0.5),
    selection= ElitismSelection(random_percent= 0.),
    attr_tasks = ['crossover', 'mutation'],
    
)
smpModel.fit(
    nb_generations= 10, nb_inds_each_task= 100, nb_inds_min= 100,
    lr = 0.1, p_const_intra= 0.0, p_mutate= 0.1,prob_search = 0.0,
    nb_epochs_stop= 50, 
    evaluate_initial_skillFactor= True
)
smpModel.run(
    nb_run= 2,
    save_path= './RESULTS/result/smpMFEA_cec17.mso'
)

Time: 00m 1.79s  100 % [====================>]  Pop_size: 2.00E+02  ,  Cost: 1.90E+01  1.87E+04  ,  
[0.5 0.5]
[1144. 1056.]
END!
Time: 00m 0.75s  100 % [====================>]  Pop_size: 2.00E+02  ,  Cost: 1.52E+01  1.50E+04  ,  
[0.5 0.5]
[1112. 1088.]
END!
DONE!
Saved
Time: 00m 1.80s  100 % [====================>]  Pop_size: 2.00E+02  ,  Cost: 2.12E+01  1.79E+04  ,  
[0.5 0.5]
[1120. 1080.]
END!
Time: 00m 0.92s  100 % [====================>]  Pop_size: 2.00E+02  ,  Cost: 2.13E+01  1.68E+04  ,  
[0.5 0.5]
[1074. 1126.]
END!
DONE!
Saved
Time: 00m 7.41s  100 % [====================>]  Pop_size: 1.00E+03  ,  Cost: 7.96E+04  1.66E+05  1.94E+05  2.93E+01  1.92E+09  2.11E+01  7.17E+01  1.55E+04  4.30E+01  4.95E+04  ,  
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
[1084. 1092. 1144. 1074. 1108. 1064. 1072. 1172. 1054. 1136.]
END!
Time: 00m 4.06s  100 % [====================>]  Pop_size: 1.00E+03  ,  Cost: 6.83E+04  1.89E+05  1.92E+05  3.12E+01  2.23E+09  2.12E+01  7.13E+01  1.38E+04  5.21E+01 

In [4]:
smpModel.print_result(['history_cost'])

1
[1.71E+01 1.69E+04]
2
[2.12E+01 1.74E+04]
3
[7.40E+04 1.78E+05 1.93E+05 3.03E+01 2.08E+09 2.11E+01 7.15E+01 1.47E+04
 4.76E+01 4.66E+04]
